# Generated by Django 3.1.7 on 2021-03-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producthunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
